### PR TITLE
Added comments

### PR DESCRIPTION
**Pull request by DarthSethious1**
I dont know how to do what Riley asked except for make a whole new branch and PR. If this isn't the way to do that, please show me how later

### CODE REVIEW

**Comment by DarthSethious1** [comment]
well I'm an idiot, this did not resolve the change riley asked for

**Comment by DarthSethious1** [comment]
i think i fixed it?

**Review by bbrk24 — APPROVED** [review]
LGTM

**Review by CClarke513 — APPROVED** [review]
We gucci

**Pull request merged**
